__author__ = 'oier'

import os

DATA_PATH = "data"
DB_NAME = "p3_june_29.db"
DB_PATH = os.path.join(DATA_PATH, DB_NAME)
THEME = "ep2018"

TALKS_JSON = "/static/data/accepted_talks.json"

STATIC = "static"
TEMPLATES = "templates"

LOCAL_TZ = "Europe/Madrid"

#IF THE THEME ALLOWES:

SPONSORS_IMAGES = 'media/sponsors' #in static folder!!!!

SOCIAL_IFRAME_SRC = "http://ep.patrick.wtf/"


#Everything autogenerated from here. You should touch nothing.
#REMEMBER TO SET THE ROUTES IN APP.PY!!!!!!!
STATIC_PATH = os.path.join(THEME, STATIC)
TEMPLATES_PATH = os.path.join(THEME, TEMPLATES)
TALKS_PATH = "%s%s%s%s" % (os.path.dirname(os.path.abspath(__file__)),"/",THEME, TALKS_JSON)

if SPONSORS_IMAGES:
    SPONSORS_IMAGES_PATH = os.path.join(THEME, STATIC, SPONSORS_IMAGES)
