import logging
import os
from pathlib import Path

LOG_LEVEL = logging.DEBUG
LOCAL_TZ = 'Europe/Madrid'

TALKS_JSON = '/static/data/accepted_talks.json'

#IF THE THEME ALLOWES:
SOCIAL_IFRAME_SRC = 'http://ep.patrick.wtf/'

#Everything autogenerated from here. You should touch nothing.
#REMEMBER TO SET THE ROUTES IN APP.PY!!!!!!!
CWD = Path(__file__).absolute().parent()
STATIC_PATH = Path('static')
TEMPLATES_PATH = Path('templates')
TALKS_PATH = CWD / STATIC_PATH / 'data' / 'accepted_talks.json'
SPONSORS_IMAGES_PATH = CWD / STATIC_PATH / 'data' / 'media' / 'sponsors'
